### ISSUE TITLE
source not found and bad trap

### ISSUE THREAD

**Issue by giorez** [Pavlos1/ppp-multi-image#1]
ciao Pavel,
I tested your script. I got following errors:

gio@aimec:~/ppp-multi-image$ sudo ./download.sh
[sudo] password for gio: 
--2024-03-07 13:49:35--  https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
Resolving xff.cz (xff.cz)... 195.181.215.36, 2001:15e8:110:3624::1
Connecting to xff.cz (xff.cz)|195.181.215.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2502556 (2.4M) [application/gzip]
Saving to: ‘ppp.tar.gz’
ppp.tar.gz          100%[===================>]   2.39M  3.54MB/s    in 0.7s    
2024-03-07 13:49:36 (3.54 MB/s) - ‘ppp.tar.gz’ saved [2502556/2502556]
./download.sh: 13: source: not found

it seems path error on line 13: "source $distro/config"

gio@aimec:~/ppp-multi-image$ sudo ./mkimage.sh -p 16G /dev/sdb
trap: ERR: bad trap

**Comment by Pavlos1** [comment]
OK, let's see..

1. I've pushed a commit to address the "source not found" error
2. `download.sh` isn't meant to be run as root, I recommend running `sudo rm -rf ~/ppp-multi-image` are re-cloning to avoid issues down the line.
3. I can't reproduce the "bad trap" issue, can you give me the output of:
```shell
ls -l $(which sh)
```

**Comment by Pavlos1** [comment]
~~Update: I can reproduce the "bad trap" error; easiest way to deal with it for now is to use `./mkimage.sh` instead of `sudo ./mkimage.sh`.~~ nevermind that works for me but would not for you

**Comment by Pavlos1** [comment]
Alright both issues should be fixed in the latest commit.

**Comment by giorez** [comment]
./download.sh work as expected.
Suggestion1: in case there is already the distro.img, could be convenient avoid to re-download the image?

regarding command ./mkimage.sh -p 16G /dev/sdb it's still in progress. I'm actually following the status trought the gnome Disks GUI. Any chance to set a status of progression during building in the terminal window? Building completed in about 10/15 minutes.

I tryed to boot my ppp from sd card. There are no distro available in the graphical menu. Plus there are 2 nonworking buttons due to boot/boot.scr (1 in arch, 1 in manjaro).

adding missing lines in
.
#/boot/extlinux/extlinux.conf
menu title Pinephone Pro Boot Menu
label l0
menu label ARCH/MANJARO/MOBIAN/PMOS
.
fixes the menu item issue as per https://github.com/Pavlos1/ppp-multi-image/pull/2

Arch booted succesfully.
Manjaro booted succesfully.
Mobian booted succesfully.
Pmos booted succesfully.

YOU DID A GREAT JOB!!!
BRAVO!

Suggestion2: could be useful to centralize in one single distros.config all the variables regarding DownloadUrlImage, PartitionName, MenuButtonName?

Suggestion3: in case yuo want to flash directly the eMMC, can you use same process and just expose eMMC to USB? > UPDATE> I just flashed eMMC via USB. Everything works like SD...

SUPER Pavel!!!

**Comment by giorez** [comment]
regarding command ./mkimage.sh -p 16G /dev/sdb it's still in progress. I'm actually following the status trought the gnome Disks GUI. Any chance to set a status of progression during building in the terminal window?

**Comment by giorez** [comment]
tryed to boot my ppp from sd card. There are no distro available in the graphical menu. Plus there are 2 nonworking buttons due to boot/boot.scr (1 in arch, 1 in manjaro).

**Comment by giorez** [comment]
Any chance to add Sailfish distro from https://github.com/sailfish-on-dontbeevil/flash-it?
thanks

**Comment by Pavlos1** [comment]
> ./download.sh work as expected. Suggestion1: in case there is already the distro.img, could be convenient avoid to re-download the image?

Implemented.
 
> regarding command ./mkimage.sh -p 16G /dev/sdb it's still in progress. I'm actually following the status trought the gnome Disks GUI. Any chance to set a status of progression during building in the terminal window? Building completed in about 10/15 minutes.

Not trivial because most of the time is spent in `rsync`. It _does_ have a `--progress` option but that would just spam your screen with every file it transfers.

EDIT: Does it take longer than the method you normally use?
 
> I tryed to boot my ppp from sd card. There are no distro available in the graphical menu. Plus there are 2 nonworking buttons due to boot/boot.scr (1 in arch, 1 in manjaro).

I've added a line now that removed `*.scr` files from all distros.
 
> adding missing lines in . #/boot/extlinux/extlinux.conf menu title Pinephone Pro Boot Menu label l0 menu label ARCH/MANJARO/MOBIAN/PMOS . fixes the menu item issue as per #2

Merged.
 
> Arch booted succesfully. Manjaro booted succesfully. Mobian booted succesfully. Pmos booted succesfully.
> 
> YOU DID A GREAT JOB!!! BRAVO!
> 
> Suggestion2: could be useful to centralize in one single distros.config all the variables regarding DownloadUrlImage, PartitionName, MenuButtonName?

I like having them separate so that there is some "index" at the root of each distro folder.

> Suggestion3: in case yuo want to flash directly the eMMC, can you use same process and just expose eMMC to USB? > UPDATE> I just flashed eMMC via USB. Everything works like SD...
> 
> SUPER Pavel!!!

**Comment by Pavlos1** [comment]
> Any chance to add Sailfish distro from https://github.com/sailfish-on-dontbeevil/flash-it? thanks

I've added `distros/sailfish` but you will probably need to experiment with it to get it working.

**Comment by giorez** [comment]
> > ./download.sh work as expected. Suggestion1: in case there is already the distro.img, could be convenient avoid to re-download the image?
> 
> Implemented.

It works

> 
> > regarding command ./mkimage.sh -p 16G /dev/sdb it's still in progress. I'm actually following the status trought the gnome Disks GUI. Any chance to set a status of progression during building in the terminal window? Building completed in about 10/15 minutes.
> 
> Not trivial because most of the time is spent in `rsync`. It _does_ have a `--progress` option but that would just spam your screen with every file it transfers.
> 
> EDIT: Does it take longer than the method you normally use?

Not longer than clasic CLI commands

**Comment by giorez** [comment]
I'm actually building on SD card exposed via USB... One more idea: on a flashed SD card, it could be ideal to get the option to reinstall or update just one single distribution.

**Comment by Pavlos1** [comment]
And that's happening at USB2 speeds I suspect.

Adding the option to reinstall a single distro is a good idea..

**Comment by giorez** [comment]
Feel free to open a PR on pine64.org to add a link to your repository.
thanks

**Comment by Pavlos1** [comment]
Single distro re-installation is now implemented (see README).

**Comment by giorez** [comment]
tested sigle distro re-installation:
util/installdistro.sh distros/sailfish /dev/sdb

worked perfectly. well done!

I also tryed to update mobian distro:
I edited config file to
URL=https://images.mobian.org/pinephonepro/weekly/mobian-rockchip-phosh-20240303.img.xz
PARTLABEL=ppp-multi-image-mobian
METHOD=img
BOOT_PT=1
ROOT_PT=2
EXTRACT=unxz

but since the new image file name is different I get following error when I run the script:

gio@aimec:~/ppp-multi-image$ util/installdistro.sh distros/mobian /dev/sdb
mke2fs 1.47.0 (5-Feb-2023)
/dev/disk/by-partlabel/ppp-multi-image-mobian contains a ext4 file system
	last mounted on /run/media/defaultuser/dd24a5f9-5b4f-4221-9196-e7a72529b77a on Fri Mar  8 18:36:08 2024
Creating filesystem with 2883584 4k blocks and 720896 inodes
Filesystem UUID: c611ec28-5dc9-4b26-a940-912968f25174
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

losetup: /home/gio/ppp-multi-image/downloads/mobian-rockchip-phosh-20240303.img: failed to set up loop device: No such file or directory

**Comment by Pavlos1** [comment]
If you update the URLs you need to re-run `download.sh`.

**Comment by giorez** [comment]
> If you update the URLs you need to re-run `download.sh`.

I would reccomend to remind this into readme file.

great job indeed.
